<?php

declare(strict_types=1);

namespace Waaseyaa\Migrate\Source\WordPress\PageBuilder;

/**
 * Structure-and-intent-preserving decoder for Elementor page bodies.
 *
 * Elementor stores a page as a JSON tree in the `_elementor_data` postmeta:
 * sections / flexbox containers > columns > widgets. This decoder walks that
 * tree and emits a normalized {@see Block} tree that keeps both the LAYOUT
 * (bands, grids, cards) and the DESIGN INTENT (band background variant +
 * background image + min-height + content alignment; heading role +
 * alignment; button variant + icon; image sizing + alignment), then renders
 * it to HTML via {@see BlockRenderer}.
 *
 * It captures what a thing IS, never how the builder drew it: hardcoded
 * colors, fonts, and builder CSS classes are dropped; {@see BlockRenderer}
 * emits framework-owned classes instead. Leaf rich text (text-editor HTML) is
 * run through {@see HtmlCleaner} so no builder classes, scripts, or
 * shortcodes survive. Structural wrappers are generated by the renderer and
 * never pass through the cleaner.
 *
 * Ported from the framework's former `waaseyaa/page-builder` package
 * (`Waaseyaa\PageBuilder\Decoder\ElementorDecoder`) as a connector-local
 * process-plugin dependency — see G-013. Deliberately narrower than the
 * source package: no decoder registry, no `DecodeRequest`/`DecodedPage`
 * envelope, and no scoped-component (`<style>`-bearing pasted HTML) handling
 * — a style-bearing text/HTML widget is cleaned like any other rich text
 * (its `<style>` tag is dropped by {@see HtmlCleaner}) rather than promoted
 * to an owned, scoped component. That narrower feature was not required by
 * G-013 and can be revisited if a payload needs it.
 *
 * @api
 */
final class ElementorTreeDecoder
{
    private const array HEADING_SIZES = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
    private const array CONTAINER_TYPES = ['container', 'section', 'column'];
    private const array SKIP_WIDGETS = ['spacer', 'divider', 'google_maps', 'video', 'loop-grid'];

    public function __construct(
        private readonly HtmlCleaner $cleaner = new HtmlCleaner(),
        private readonly BlockRenderer $renderer = new BlockRenderer(),
    ) {}

    /**
     * Decode a raw `_elementor_data` JSON payload into rendered HTML.
     *
     * Returns null when the payload is absent/empty (`''`, `'[]'`), is not
     * valid JSON, does not decode to an array, or decodes to a tree that
     * yields no renderable blocks (e.g. every widget is skip-listed). Callers
     * treat null as "nothing decoded" and fall back to the original content.
     */
    public function decode(string $rawJson): ?string
    {
        $trimmed = \trim($rawJson);
        if ($trimmed === '' || $trimmed === '[]') {
            return null;
        }

        $tree = \json_decode($rawJson, true);
        if (\json_last_error() !== \JSON_ERROR_NONE || !\is_array($tree)) {
            return null;
        }

        $blocks = $this->walk($tree, 0);
        if ($blocks === []) {
            return null;
        }

        return $this->renderer->render($blocks);
    }

    /**
     * @param list<mixed> $elements
     * @return list<Block>
     */
    private function walk(array $elements, int $depth): array
    {
        $blocks = [];
        foreach ($elements as $el) {
            if (!\is_array($el)) {
                continue;
            }
            $elType = \is_string($el['elType'] ?? null) ? $el['elType'] : '';
            if ($elType === 'widget') {
                $b = $this->widgetBlock($el);
            } elseif (\in_array($elType, self::CONTAINER_TYPES, true)) {
                $b = $this->containerBlock($el, $depth);
            } else {
                $b = null;
            }
            if ($b !== null) {
                $blocks[] = $b;
            }
        }

        return $blocks;
    }

    /**
     * @param array<string, mixed> $el
     */
    private function containerBlock(array $el, int $depth): ?Block
    {
        $settings = \is_array($el['settings'] ?? null) ? $el['settings'] : [];
        $rawChildren = \is_array($el['elements'] ?? null) ? $el['elements'] : [];

        $decoded = $this->walk($rawChildren, $depth + 1);
        if ($decoded === []) {
            return null;
        }

        $childContainers = [];
        foreach ($rawChildren as $c) {
            if (\is_array($c) && \in_array($c['elType'] ?? '', self::CONTAINER_TYPES, true)) {
                $childContainers[] = $c;
            }
        }
        $nContainers = \count($childContainers);

        $styled = isset($settings['border_radius']) || isset($settings['box_shadow_box_shadow_type']);

        if ($styled && $nContainers === 0) {
            return new Block(Block::CARD, [], '', $decoded);
        }

        $cardChildren = 0;
        foreach ($decoded as $d) {
            if ($d->type === Block::CARD) {
                ++$cardChildren;
            }
        }

        $fd = \is_string($settings['flex_direction'] ?? null) ? $settings['flex_direction'] : '';
        $allSimple = true;
        foreach ($childContainers as $cc) {
            if ($this->hasNestedContainer($cc)) {
                $allSimple = false;
                break;
            }
        }

        $layout = 'stack';
        if ($cardChildren >= 2) {
            $layout = 'grid';
        } elseif ($fd === 'row' && $nContainers >= 2 && $allSimple) {
            $layout = 'grid';
        }

        $bg = $settings['background_background'] ?? null;
        $variant = $bg === 'gradient' ? 'gradient' : ($bg === 'classic' ? 'soft' : 'plain');

        $data = ['variant' => $variant, 'layout' => $layout];

        // Design intent: minimum height (hero height), content alignment, and an
        // optional background image. Hardcoded colors are intentionally dropped;
        // the renderer applies brand tokens.
        $minHeight = $this->pxSize($settings['min_height'] ?? null);
        if ($minHeight !== null && $minHeight > 0) {
            $data['min_height'] = $minHeight;
        }
        $align = $this->mapJustify($settings['flex_justify_content'] ?? null);
        if ($align !== null) {
            $data['align'] = $align;
        }
        $bgImage = $settings['background_image'] ?? null;
        if (\is_array($bgImage) && \is_string($bgImage['url'] ?? null) && $bgImage['url'] !== '') {
            $data['bg_image'] = $this->raw($bgImage['url']);
        }

        return new Block(Block::BAND, $data, '', $decoded);
    }

    /**
     * @param array<string, mixed> $el
     */
    private function hasNestedContainer(array $el): bool
    {
        foreach (($el['elements'] ?? []) as $c) {
            if (\is_array($c) && \in_array($c['elType'] ?? '', self::CONTAINER_TYPES, true)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param array<string, mixed> $el
     */
    private function widgetBlock(array $el): ?Block
    {
        $type = \is_string($el['widgetType'] ?? null) ? $el['widgetType'] : '';
        $s = \is_array($el['settings'] ?? null) ? $el['settings'] : [];

        if (\in_array($type, self::SKIP_WIDGETS, true)) {
            return null;
        }

        return match ($type) {
            'heading' => $this->headingBlock($s),
            'text-editor', 'theme-post-content' => $this->textBlock($s['editor'] ?? ''),
            'image' => $this->imageBlock($s),
            'button' => $this->buttonBlock($s),
            'icon-box' => $this->iconBoxBlock($s),
            'icon-list' => $this->listBlock($s),
            'image-carousel' => $this->galleryBlock($s),
            'shortcode', 'html' => $this->textBlock($s['shortcode'] ?? ($s['html'] ?? '')),
            default => $this->unknownBlock($s),
        };
    }

    /** @param array<string, mixed> $s */
    private function headingBlock(array $s): ?Block
    {
        $text = $this->raw($s['title'] ?? '');
        if ($text === '') {
            return null;
        }
        $size = \is_string($s['header_size'] ?? null) && \in_array($s['header_size'], self::HEADING_SIZES, true)
            ? $s['header_size']
            : 'h2';

        $data = ['level' => (int) \substr($size, 1), 'text' => $text];
        $align = $this->mapAlign($s['align'] ?? null);
        if ($align !== null) {
            $data['align'] = $align;
        }

        return new Block(Block::HEADING, $data);
    }

    private function textBlock(mixed $raw): ?Block
    {
        $rawHtml = \is_string($raw) ? $raw : (\is_scalar($raw) ? (string) $raw : '');
        $html = $this->cleaner->clean($rawHtml);

        return $html === '' ? null : new Block(Block::TEXT, [], $html);
    }

    /** @param array<string, mixed> $s */
    private function imageBlock(array $s): ?Block
    {
        $image = $s['image'] ?? null;
        if (!\is_array($image)) {
            return null;
        }
        $url = $this->raw($image['url'] ?? '');
        if ($url === '') {
            return null;
        }
        $alt = $this->raw($image['alt'] ?? '');

        $data = ['url' => $url, 'alt' => $alt];
        $width = $s['width'] ?? null;
        if (\is_array($width) && \is_numeric($width['size'] ?? null)) {
            $unit = \in_array($width['unit'] ?? 'px', ['px', '%', 'vw', 'em', 'rem'], true) ? $width['unit'] : 'px';
            $data['width'] = ((string) (int) $width['size']) . $unit;
        }
        $align = $this->mapAlign($s['align'] ?? null);
        if ($align !== null) {
            $data['align'] = $align;
        }

        return new Block(Block::IMAGE, $data);
    }

    /** @param array<string, mixed> $s */
    private function buttonBlock(array $s): ?Block
    {
        $text = $this->raw($s['text'] ?? '');
        if ($text === '') {
            return null;
        }
        $link = $s['link'] ?? null;
        $url = \is_array($link) ? $this->raw($link['url'] ?? '') : '';

        $data = ['text' => $text, 'url' => $url === '' ? '#' : $url];
        $icon = $this->iconName($s['selected_icon'] ?? null);
        if ($icon !== '') {
            $data['icon'] = $icon;
            $data['icon_align'] = ($s['icon_align'] ?? '') === 'left' ? 'left' : 'right';
        }

        return new Block(Block::BUTTON, $data);
    }

    /** @param array<string, mixed> $s */
    private function iconBoxBlock(array $s): ?Block
    {
        $title = $this->raw($s['title_text'] ?? '');
        $desc = $this->raw($s['description_text'] ?? '');
        if ($title === '' && $desc === '') {
            return null;
        }
        $link = $s['link'] ?? null;
        $url = \is_array($link) ? $this->raw($link['url'] ?? '') : '';

        return new Block(Block::ICON_BOX, ['title' => $title, 'desc' => $desc, 'url' => $url]);
    }

    /** @param array<string, mixed> $s */
    private function listBlock(array $s): ?Block
    {
        $items = $s['icon_list'] ?? null;
        if (!\is_array($items) || $items === []) {
            return null;
        }
        $lis = '';
        foreach ($items as $item) {
            if (!\is_array($item)) {
                continue;
            }
            $text = $this->raw($item['text'] ?? '');
            if ($text === '') {
                continue;
            }
            $link = $item['link'] ?? null;
            $url = \is_array($link) ? $this->raw($link['url'] ?? '') : '';
            $esc = $this->esc($text);
            $lis .= $url !== ''
                ? '<li><a href="' . $this->esc($url) . '">' . $esc . '</a></li>'
                : '<li>' . $esc . '</li>';
        }

        return $lis === '' ? null : new Block(Block::LIST, [], "<ul>{$lis}</ul>");
    }

    /** @param array<string, mixed> $s */
    private function galleryBlock(array $s): ?Block
    {
        $items = $s['carousel'] ?? null;
        if (!\is_array($items) || $items === []) {
            return null;
        }
        $figs = '';
        foreach ($items as $item) {
            if (!\is_array($item)) {
                continue;
            }
            $url = $this->raw($item['url'] ?? '');
            if ($url === '') {
                continue;
            }
            $alt = $this->raw($item['alt'] ?? '');
            $figs .= '<figure class="pb-image"><img src="' . $this->esc($url) . '" alt="' . $this->esc($alt) . '" loading="lazy"></figure>';
        }

        return $figs === '' ? null : new Block(Block::GALLERY, [], '<div class="pb-gallery">' . $figs . '</div>');
    }

    /**
     * Unknown widget: salvage any text-bearing settings as a clean block.
     *
     * @param array<string, mixed> $s
     */
    private function unknownBlock(array $s): ?Block
    {
        $html = '';
        if (\is_string($s['title'] ?? null) && $s['title'] !== '') {
            $html .= '<h3>' . $this->esc($this->raw($s['title'])) . '</h3>';
        }
        foreach (['editor', 'html', 'shortcode'] as $k) {
            if (\is_string($s[$k] ?? null) && $s[$k] !== '') {
                $html .= $s[$k];
            }
        }
        foreach (['text', 'description', 'caption', 'description_text'] as $k) {
            if (\is_string($s[$k] ?? null) && $s[$k] !== '') {
                $html .= '<p>' . $this->esc($this->raw($s[$k])) . '</p>';
            }
        }
        $clean = $this->cleaner->clean($html);

        return $clean === '' ? null : new Block(Block::HTML, [], $clean);
    }

    /** Parse an Elementor size control ({unit,size}) to an integer pixel value. */
    private function pxSize(mixed $v): ?int
    {
        if (!\is_array($v)) {
            return null;
        }
        $unit = $v['unit'] ?? 'px';
        $size = $v['size'] ?? null;
        if ($unit !== 'px' || !\is_numeric($size)) {
            return null;
        }

        return (int) $size;
    }

    private function mapJustify(mixed $v): ?string
    {
        return match ($v) {
            'center' => 'center',
            'space-between' => 'between',
            'flex-end' => 'end',
            'flex-start' => 'start',
            default => null,
        };
    }

    private function mapAlign(mixed $v): ?string
    {
        return match ($v) {
            'center' => 'center',
            'right' => 'right',
            'left' => 'left',
            default => null,
        };
    }

    /**
     * Normalize an Elementor icon control ({value:'fas fa-arrow-right'}) to a
     * builder-agnostic icon token ('arrow-right'). {@see BlockRenderer} maps
     * known tokens to brand inline SVGs; unknown tokens render no icon (clean).
     */
    private function iconName(mixed $icon): string
    {
        $value = '';
        if (\is_array($icon) && \is_string($icon['value'] ?? null)) {
            $value = $icon['value'];
        } elseif (\is_string($icon)) {
            $value = $icon;
        }
        if ($value === '') {
            return '';
        }
        if (\preg_match('/fa-([a-z0-9-]+)/', $value, $m) === 1) {
            return $m[1];
        }

        return '';
    }

    private function raw(mixed $value): string
    {
        $s = \is_string($value) ? $value : (\is_scalar($value) ? (string) $value : '');

        return \html_entity_decode(\trim($s), \ENT_QUOTES | \ENT_SUBSTITUTE, 'UTF-8');
    }

    private function esc(string $value): string
    {
        return \htmlspecialchars($value, \ENT_QUOTES | \ENT_SUBSTITUTE, 'UTF-8');
    }
}
